### ISSUE TITLE
Mute videofeed?

### ISSUE THREAD

**Issue by ghost** [mykle1/MMM-EARTH-Live#5] opened 2020-12-15 18:18 UTC
is there an easy way to do this?

**Comment by mykle1** [comment] 2020-12-16 01:35
You could try this in your custom.css file

iframe {
    volume: silent;
}

or

adding this to the ifame element in the js file

iframe.contentWindow.postMessage('{"method":"setVolume", "value":0}','*');

or

If your mirror has access to a mouse you can hover over the module while it running and click the sound icon and mute there.

I have not tried any of these as the module works as I intended for the most part. I am closing the issue as it really is a request for a feature and not an issue with the module as written.

Thanks and good luck

**Closed as completed by mykle1** 2020-12-16 01:35 UTC

**Comment by JoshuaShelswell** [comment] 2020-12-18 09:32
none of those methods work, tried all sorts of places in the js file, ill give up asking and look into it myself since apparently its a feature to have volume control on anything thats playing anything, hasnt been the case since the 1930s

**Comment by JoshuaShelswell** [comment] 2020-12-18 10:54
put in 

iframe.setVolume = ("muted");

on line 38, havent heard them in an hour or so, hopefully that worked out

**Comment by JoshuaShelswell** [comment] 2020-12-18 10:57
guess it didnt work, they still talking

**Comment by mykle1** [comment] 2020-12-18 20:21
I might have looked into it further until I read your response to my last post, you ungrateful whining bitch. Delete any modules of mine that you use so you have nothing to complain about.

**Comment by mykle1** [comment] 2020-12-18 20:24
I might have looked into it further until I read your response to my last post, you ungrateful whining bitch. Delete any modules of mine that you use so you have nothing to complain about.

**Comment by JoshuaShelswell** [comment] 2020-12-20 10:26
> 
> 
> I might have looked into it further until I read your response to my last post, you ungrateful whining bitch. Delete any modules of mine that you use so you have nothing to complain about.

im sorry im trying to make the volume work on your application and im trying things myself, i might give a shot at rebuilding a module myself which you should be encouraging since im new to this, dont need to use profane languages or call people bitches either its super unprofessional, and im trying to bring up an issue that i and probably other people have with it, im sorry you cant take any kinda constructive critisizm and you cant discern whats a feature request vs how it was intended to run since you literally made functionalities in your code that verifies what it was intended for, didnt mean to piss you off or offend you, i already said that i appreciate your work in a post the other day, sorry if you're having issues but its not with me
